# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ Maven ]
  pull_request:
    branches: [ Maven ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Java SDK (14.0.1)
        uses: actions/setup-java@v1
        with:
          java-version: 14.0.1
      - name: Build And Test With Maven
        run: mvn -B package --file pom.xml